# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://8.219.231.172:3306/nft?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 20-20000Hz
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
      default-auto-commit: true
      filters: stat,wall
      initial-size: 1
      log-abandoned: true
      max-active: 200
      max-pool-prepared-statement-per-connection-size: 1000
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      pool-prepared-statements: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 180000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 1000
      validation-query: select 1
mybatis-plus:
  # mybatis-plus配置
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.libi.bean
  configuration:
    local-cache-scope: statement
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1

nft:
  common:
    minio-config:
      end-point: "http://8.219.231.172:9000"
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: 28e2bb94568945009b02c7a955a15b1f
      bucket: nft-tool
      server-url: "http://8.219.231.172:9000"
  web:
    chain-config:
#      chain-url: "https://goerli.infura.io/v3/27e2a45df8a342829feba9d79ed8a564"
#      admin-account-address: "0xE30B579B61B4f0C4762aB93742B258f873789805"
#      admin-account-private-key: "626b5aa28aacfd5ac77467d18432bf01de0edbf17d9d8b30e64c9d3cfd5cd274"
#      contract-address: "0xcA1ca68fD664a3E9F13A03AF2AA8ad8343800Efe"
#      target-address: "0xD7c6C3E8afa82dAAbbc67BcBE9524DD108A69982"

      chain-url: "http://8.219.231.172:9090"
      admin-account-address: "0x1fB8743F8E8Ef7864fc1540A8900CAc767465C60"
      admin-account-private-key: "0x2352956032ca0801cf2ae209a801a3160080941bb35feb1cbfdfd866ce5f0bf5"
      contract-address: "0x5349aa8f5e27db7a84166ee6ecda5c54d9c35fde"
      target-address: "0x9F7f497465d19B79302E930c03E9e8b10deF724D"