# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://137.184.118.155:3306/nft?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: gEqs9.8mPers
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
      default-auto-commit: true
      filters: stat,wall
      initial-size: 1
      log-abandoned: true
      max-active: 200
      max-pool-prepared-statement-per-connection-size: 1000
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      pool-prepared-statements: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 180000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 1000
      validation-query: select 1
mybatis-plus:
  # mybatis-plus配置
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.libi.bean
  configuration:
    local-cache-scope: statement
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1

nft:
  common:
    minio-config:
      end-point: "http://137.184.118.155:9000"
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: 28e2bb94568945009b02c7a955a15b1f
      bucket: nft-tool
      server-url: "http://137.184.118.155:9000"
  web:
    chain-config:
      chain-url: "http://127.0.0.1:7545"
      admin-account-address: "0xdC16F215cCd2362D317e47777DC9AbD45eE6406b"
      admin-account-private-key: "b8c9171e3274b8d5bf6a2f6f520d03d4c9a9e397d70f8d26d7585d692dbd11d8"
      contract-address: "0xcA1ca68fD664a3E9F13A03AF2AA8ad8343800Efe"
      target-address: "0xdC16F215cCd2362D317e47777DC9AbD45eE6406b"
